import './globals.css'
import { Inter } from 'next/font/google'
import Header from './Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'News app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />

      <body className={`${inter.className} bg-gray-100 dark:bg-zinc-100 transition-all duration-7`}>
        <Header />
          <div className="max-w-6xl mx-auto">
          {children}
          </div>
        </body>
    </html>
  )
}
