import './globals.css'
import { Inter } from 'next/font/google'
import Header from './Header'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'News app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />

      <body className={inter.className}>
        <Header />
          {children}
        </body>
    </html>
  )
}
